-- MySQL Script generated by MySQL Workbench
-- Thu Jul 24 13:30:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema hotel_managment
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel_managment` ;

-- -----------------------------------------------------
-- Schema hotel_managment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_managment` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `hotel_managment` ;

-- -----------------------------------------------------
-- Table `hotel_managment`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`booking` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`booking` (
  `id_booking` INT NOT NULL,
  `id_client` INT NOT NULL,
  `number_room` VARCHAR(10) NOT NULL,
  `date_reservation` DATE NOT NULL,
  `date_check_in` DATE NOT NULL,
  `date_check_out` DATE NOT NULL,
  `status_booking` ENUM('reservat', 'canceled', 'completed') NOT NULL DEFAULT 'reservat',
  `total_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_booking`),
  CONSTRAINT `fk_id_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `hotel_managment`.`clients` (`id_client`),
  CONSTRAINT `fk_number_room`
    FOREIGN KEY (`number_room`)
    REFERENCES `hotel_managment`.`room` (`number_room`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_id_client` ON `hotel_managment`.`booking` (`id_client` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_number_room` ON `hotel_managment`.`booking` (`number_room` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`booking_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`booking_services` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`booking_services` (
  `id_booking` INT NOT NULL,
  `id_services` SMALLINT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  PRIMARY KEY (`id_booking`, `id_services`),
  CONSTRAINT `fk_id_booking`
    FOREIGN KEY (`id_booking`)
    REFERENCES `hotel_managment`.`booking` (`id_booking`),
  CONSTRAINT `fk_id_services`
    FOREIGN KEY (`id_services`)
    REFERENCES `hotel_managment`.`servicess` (`id_services`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_id_services` ON `hotel_managment`.`booking_services` (`id_services` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`clients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL DEFAULT NULL,
  `birth_date` DATE NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `citizenship` VARCHAR(100) NOT NULL,
  `document_type` VARCHAR(50) NOT NULL,
  `document_number` VARCHAR(50) NOT NULL,
  `document_issued_by` VARCHAR(150) NULL DEFAULT NULL,
  `document_issue_date` DATE NULL DEFAULT NULL,
  `address` TEXT NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`logs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`logs` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `action` TEXT NOT NULL,
  `log_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_log`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel_managment`.`users` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_user_id` ON `hotel_managment`.`logs` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`maintenance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`maintenance` (
  `id_maintenance` INT NOT NULL AUTO_INCREMENT,
  `number_room` VARCHAR(10) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `reason` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_maintenance`),
  CONSTRAINT `fk_number_room_maintenance`
    FOREIGN KEY (`number_room`)
    REFERENCES `hotel_managment`.`room` (`number_room`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_number_room_maintenance` ON `hotel_managment`.`maintenance` (`number_room` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`payments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`payments` (
  `id_payment` INT NOT NULL AUTO_INCREMENT,
  `id_booking` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_type` ENUM('cash', 'card') NOT NULL,
  `status` ENUM('paid', 'unpaid') NULL DEFAULT 'paid',
  PRIMARY KEY (`id_payment`),
  CONSTRAINT `fk_id_booking_payments`
    FOREIGN KEY (`id_booking`)
    REFERENCES `hotel_managment`.`booking` (`id_booking`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_id_booking_payments` ON `hotel_managment`.`payments` (`id_booking` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`room` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`room` (
  `number_room` VARCHAR(10) NOT NULL,
  `price_room` DECIMAL(10,2) NOT NULL,
  `capacity` SMALLINT NOT NULL,
  `status_room` ENUM('free', 'occupied', 'maintenance') NOT NULL,
  `comfort_level` ENUM('standard', 'deluxe', 'suite') NOT NULL,
  PRIMARY KEY (`number_room`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`servicess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`servicess` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`servicess` (
  `id_services` SMALLINT NOT NULL,
  `name_services` VARCHAR(255) NOT NULL,
  `description_services` TEXT NULL DEFAULT NULL,
  `price_services` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_services`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`staff` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`staff` (
  `id_Staff` INT NOT NULL AUTO_INCREMENT,
  `last_name_staff` VARCHAR(100) NOT NULL,
  `first_name_staff` VARCHAR(100) NOT NULL,
  `middle_name_staff` VARCHAR(100) NULL DEFAULT NULL,
  `job_title` ENUM('admin', 'receptionist', 'cleaner', 'manager') NULL DEFAULT 'receptionist',
  `phone` VARCHAR(20) NOT NULL,
  `home_address` TEXT NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Staff`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `login` ON `hotel_managment`.`staff` (`login` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hotel_managment`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_managment`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hotel_managment`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('guest', 'staff', 'admin') NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username` ON `hotel_managment`.`users` (`username` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
